# Generated by Django 5.0.4 on 2024-04-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_completedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedtask',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedtask',
            name='status',
            field=models.CharField(default='Completed', max_length=20),
        ),
        migrations.AddField(
            model_name='completedtask',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
