# Generated by Django 5.0.4 on 2024-04-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_completedtask_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtask',
            name='task',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
